server:
  port: 8080
  servlet:
    context-path: /website

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangductoan290803@gmail.com
    password: wqzt nhin yhxz bkrc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: "jdbc:mysql://localhost:3306/websitemohinh"
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


upload:
  image:
    dir: uploads/
jwt:
  signerKey: "ywh+Jbt9f82I2/T9b+e7b2zzYQ0j8oWekdab6rqdh/ZCouY5rgrM0/B4dm89WP91"



